// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_for_access_token_token_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Task = {
    title: string;
    description?: string | null;
    due_date?: string | null;
    id: string;
    owner_id: string;
    updated_at: string;
    created_at: string;
};

export type TaskCreate = {
    title: string;
    description?: string | null;
    due_date?: string | null;
};

export type TaskUpdate = {
    title: string;
    description?: string | null;
    due_date?: string | null;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type User = {
    email: string;
    id: string;
    items?: Array<Task>;
};

export type UserCreate = {
    email: string;
    password: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginForAccessTokenTokenPostData = {
    formData: Body_login_for_access_token_token_post;
};

export type LoginForAccessTokenTokenPostResponse = Token;

export type ReadUsersMeUsersMeGetResponse = User;

export type ReadOwnTasksTasksGetResponse = Array<Task>;

export type CreateTaskForUserTasksPostData = {
    requestBody: TaskCreate;
};

export type CreateTaskForUserTasksPostResponse = Task;

export type ReadTaskTasksTaskIdGetData = {
    taskId: string;
};

export type ReadTaskTasksTaskIdGetResponse = Task;

export type DeleteTaskTasksTaskIdDeleteData = {
    taskId: string;
};

export type DeleteTaskTasksTaskIdDeleteResponse = Task;

export type UpdateTaskTasksTaskIdPutData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type UpdateTaskTasksTaskIdPutResponse = Task;

export type CreateUserUsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserUsersPostResponse = User;

export type $OpenApiTs = {
    '/token': {
        post: {
            req: LoginForAccessTokenTokenPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Token;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/me/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: User;
            };
        };
    };
    '/tasks/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Task>;
            };
        };
        post: {
            req: CreateTaskForUserTasksPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/tasks/{task_id}': {
        get: {
            req: ReadTaskTasksTaskIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteTaskTasksTaskIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: UpdateTaskTasksTaskIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/': {
        post: {
            req: CreateUserUsersPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: User;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};